version: '3'

services:

  lb:
    build: services/lb
    ports: ['${HTTP_PORT}:80']
    links: ['osticket', 'xwiki', 'jenkins']

  osticket:
    image: campbellsoftwaresolutions/osticket
    env_file: ['osticket.env']
    environment: ['INSTALL_EMAIL=${ADMIN_EMAIL}']
    links: ['osticket_db']

  osticket_db:
    image: mysql:5
    env_file: ['osticket.env']
    volumes: ['./volumes/osticket_db:/var/lib/mysql']

  xwiki:
    image: xwiki:mysql-tomcat
    env_file: ['xwiki.env']
    links: ['xwiki_db']

  xwiki_db:
    build: services/xwiki_db
    env_file: ['xwiki.env']
    volumes: ['./volumes/xwiki_db:/var/lib/mysql']

  jenkins:
    image: jenkins/jenkins:lts
    ports: ['50000:5000']
    volumes: ['./volumes/jenkins:/var/jenkins_home']

  smtp:
    image: namshi/smtp
    environment: ['GMAIL_USER=${GMAIL_USER}', 'GMAIL_PASSWORD=${GMAIL_PASSWORD}']

  backup:
    image: javanile/backup
    volumes:
      - './backup:/backup/backup'
      - './osticket.env:/backup/service/osticket'
