version: '3'

services:

  lb:
    build: services/lb
    ports: ['${HTTP_PORT}:80']
    links: ['osticket', 'redmine']

  osticket:
    image: campbellsoftwaresolutions/osticket
    env_file: ['osticket.env']
    links: ['osticket_db']

  osticket_db:
    image: mysql:5
    env_file: ['osticket.env']
    volumes: ['./volumes/osticket_db:/var/lib/mysql']

  redmine:
    image: redmine

  smtp:
    image: namshi/smtp

