version: '3'

services:

  lb:
    build: services/lb
    ports: ['${AGENCY_PORT}:80']
    links: ['osticket', 'redmine']

  osticket:
    image: campbellsoftwaresolutions/osticket
    env_file: ['osticket.env']
    links: ['osticket_db']

  osticket_db:
    image: mysql:5
    env_file: ['osticket.env']


  redmine:
    image: redmine
