FROM nginx:1.12.2-alpine

COPY nginx.conf /etc/nginx/nginx.conf
COPY xwiki.conf /etc/nginx/conf.d/xwiki.conf
COPY osticket.conf /etc/nginx/conf.d/osticket.conf
COPY redmine.conf /etc/nginx/conf.d/redmine.conf
COPY jenkins.conf /etc/nginx/conf.d/jenkins.conf
